### ISSUE TITLE
你好，我按照你的教程安装，但是无法运行。

### ISSUE THREAD

**Issue by vincentCheng** [daruk-framework/daruk#16]
我是在win10下，使用vscode运行你的代码的。

**Describe the bug**
npm run dev 之后无法运行啊。

错误如下：

HuangGang@PC-20181118AWSO MINGW64 /d/DarukWorkSpace/daruk-example
$ npm run dev

> daruk-example@0.1.0 dev D:\DarukWorkSpace\daruk-example
> cross-env NODE_ENV=dev nodemon --exec ts-node --files ./src/app.ts

[nodemon] 1.19.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `ts-node --files ./src/app.ts`
[2019-5-5 17:25:22] [debug] [init] [config] 
[2019-5-5 17:25:22] [debug] [init] [util] ["testUtil","sort"]
[2019-5-5 17:25:22] [debug] [init] [glue] ["mysql"]
[2019-5-5 17:25:22] [debug] [init] [middleware] ["koa-handle-error","koa-favicon","koa-static","koa-bodyparser","koa-test-mid","koa-ejs"]
[2019-5-5 17:25:22] [debug]  AssertionError [ERR_ASSERTION]: controller class name should be
'\contact\index' ( CamelCase style and match route path ) in path: D:\DarukWorkSpace\daruk-example\src\controllers\contact\index.ts
    at routers.forEach (D:\DarukWorkSpace\daruk-example\node_modules\daruk\src\core\daruk_loader.ts:112:7)
    at Array.forEach (<anonymous>)
    at DarukLoader.loadController (D:\DarukWorkSpace\daruk-example\node_modules\daruk\src\core\daruk_loader.ts:92:13)
    at DarukCore.initEnv (D:\DarukWorkSpace\daruk-example\node_modules\daruk\src\core\daruk_init_module.ts:73:12)
    at new DarukCore (D:\DarukWorkSpace\daruk-example\node_modules\daruk\src\core\daruk_core.ts:96:10)
    at Object.<anonymous> (D:\DarukWorkSpace\daruk-example\src\daruk.init.ts:11:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (D:\DarukWorkSpace\daruk-example\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\DarukWorkSpace\daruk-example\node_modules\ts-node\src\index.ts:442:12)
logType:     daruk-example
env:         dev
fileinfo:    \node_modules\daruk\src\core\daruk_core.ts:239:21
msg:         process is exiting
os_hostname: PC-20181118AWSO
level:       info
timestamp:   1557048322594
------------------------------
logType:     daruk-example
env:         dev
fileinfo:    \node_modules\daruk\src\core\daruk_core.ts:243:21
msg:         process exited: 1
os_hostname: PC-20181118AWSO
level:       info
timestamp:   1557048322598
------------------------------
[nodemon] app crashed - waiting for file changes before starting...

**Comment by xiaojue** [comment]
@vincentCheng  应该是路径反斜杠的问题，我明天打一个补丁修复一下，再通知你更新方法。
这里引起来的问题是在unix下路径是 `/xx/xx/xx`,正则写的校验也是，看了一下你的报错，应该是windows下的路径匹配是`\xx\xx\xx`格式了。

@Youjingyu 我明天检查一下所有的replace地方，找个windows的电脑试试一下，升级到0.4.x。

**Comment by vincentCheng** [comment]
@xiaojiu
感谢感谢
如果你有win10的话也请先安装一下。

**Comment by xiaojue** [comment]
> @xiaojiu
> 感谢感谢
> 如果你有win10的话也请先安装一下。

我正在装win7的虚拟机，应该是一样的，在windows下的兼容性确实之前没有做，我们team都是mac开发的，修复好了我再关这个issues哈，应该明天下午就ok了。

**Comment by xiaojue** [comment]
脚手架和daruk升级到0.4.0版本，已经发布测试。
